CREATE SCHEMA IF NOT EXISTS comment_schema;

CREATE TABLE IF NOT EXISTS comment_schema.comments (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    author_name VARCHAR(250),
    text VARCHAR(1000) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP WITHOUT TIME ZONE
);