server:
  port: 0

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5431}/stats
    username: ${DB_USERNAME:stats}
    password: ${DB_PASSWORD:stats}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

grpc:
  server:
    port: 0
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

analyzer:
  kafka:
    bootstrap: "localhost:9092"
    consume.attempt.timeout: 100
    topic:
      actions: "stats.user-actions.v1"
      similarity: "stats.events-similarity.v1"
    producer:
      properties:
        bootstrap.servers: "localhost:9092"
        key.serializer: "org.apache.kafka.common.serialization.VoidSerializer"
        value.serializer: "ru.yandex.practicum.ewm.stats.kafka.serializer.GeneralAvroSerializer"
        retries: 3
    consumer:
      properties:
        bootstrap.servers: "localhost:9092"
        group.id: "analyzer-group"
        key.deserializer: "org.apache.kafka.common.serialization.VoidDeserializer"
        value.deserializer: "ru.yandex.practicum.ewm.stats.kafka.deserializer.GeneralAvroDeserializer"
        auto.offset.reset: "earliest"
        enable.auto.commit: "false"
        max.poll.records: "100"
