CREATE TABLE IF NOT EXISTS hit (
    hit_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    create_date TIMESTAMP NOT NULL
);